name: deploy
on:
  pull_request:
    branches:
      - 'release/**'
    tags:
      - "v-*"

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    name: Build and deploy
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          ref: ${{ github.head_ref }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Assemble release
        run: ./gradlew assembleRelease

      - name: Upload actifact to Firebase App Distribution
        run: ./gradlew appDistributionUploadRelease
