name: deploy
on:
  push:
    branches:
      - 'release/**'
    tags:
      - "v-*"

jobs:
  deploy:
    name: Build and deploy
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          ref: ${{ github.head_ref }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Assemble release
        run: ./gradlew assembleRelease

      - name: Upload actifact to Firebase App Distribution
        uses: burhankhanzada/firebase_app_distribution_github_action@main
        with:
          service_account_key_json: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          app_id: ${{ secrets.FIREBASE_APP_ID }}
          app: androidApp/build/outputs/apk/release/androidApp-release.apk
          groups: all
          release_notes_file: "release_notes.txt"
