name: deploy
on:
  push:
    branches:
      - 'release/**'
    tags:
      - "v-*"

jobs:
  deploy:
    name: Build and deploy
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          ref: ${{ github.head_ref }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Assemble release
        run: ./gradlew assembleRelease

      - name: Upload actifact to Firebase App Distribution
        uses: hasretsariyer/firebase-app-distribution-github-action@v1
        with:
          app_id: ${{secrets.FIREBASE_APP_ID}}
          firebase_token: ${{ secrets.FIREBASE_DISTRIBUTION_TOKEN }}
          groups: testers
          file: androidApp/build/outputs/apk/release/androidApp-release.apk
